name: Deploy Angular App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Instalar Angular CLI
      run: npm install -g @angular/cli

    - name: Instalar dependencias
      run: npm install

    - name: Construir aplicación Angular
      run: ng build --prod


    - name: Limpiar caché
      run: npm cache clean --force
